### ISSUE TITLE
Unauthorized When Attempting to Run in Docker

### ISSUE THREAD

**Issue by maxemoose** [synesthesiam/homeassistant-satellite#32]
### Current Behavior:
Set up a Docker compose copied directly from the README. Ran "docker compose up -d" to spin up a container and got the following error when attempting to pull the container image:

```
✘ homeassistant-satellite Error                                                                                              0.4s 
Error response from daemon: Head "https://ghcr.io/v2/synesthesiam/homeassistant-satellite/manifests/latest": unauthorized
```

### Expected Behavior:
The Docker image downloaded without authorization being necessary

### Steps To Reproduce:
1. Attempt to pull the Docker image using this command:
```
docker pull ghcr.io/synesthesiam/homeassistant-satellite:latest
```

### Environment:
Raspberry Pi 4B 4GB
- OS: Ubuntu 22.04
- Docker: 24.0.6

**Comment by scottshanafelt** [comment]
I was just going to post similar.  I can't pull the docker image, it's not public or doesn't exist

**Comment by andreasbrett** [comment]
@synesthesiam Could you please check this? I would really like to test the latest Docker image and @Links2004 image hasn't been updated after the PR got merged.

**Comment by synesthesiam** [comment]
@Links2004 Thanks for the information! This is my first time using Github for Docker images :slightly_smiling_face:

**Comment by andreasbrett** [comment]
thanks, works for me now! the docker image is not the latest though - https://github.com/synesthesiam/homeassistant-satellite/commit/ba44dbd99806aa30bebbbf85300688c77b3f1d05 is not (yet) included in the image.

**Comment by maxemoose** [comment]
Works for me too, thanks!

**Comment by synesthesiam** [comment]
Updated :slightly_smiling_face:
