### ISSUE TITLE
awake-sound and done-sound causing error (docker container)

### ISSUE THREAD

**Issue by khalob** [synesthesiam/homeassistant-satellite#67]
First off, thank you for this great repo! I noticed this issue and it might be user error, but...

If I include the `awake` or `done` sound configurations I get an EOF error after triggering the wakeword. Sound comes out of my speaker and my mic is able to fully trigger the wakeword + capture the intent without issues when these configurations are not present. 

Configurations causing issue for me:
```
--awake-sound sounds/awake.wav --done-sound sounds/done.wav
```

I'm running this within a docker container using the following. I have opted to use a custom wakeword model. Speaker/Mic hardware is the Anker S330:
```
docker run --rm -it \
    --name 'ha-satellite' \
    --device /dev/snd \
    --group-add=audio \
    ghcr.io/synesthesiam/homeassistant-satellite:latest \
    --host my_HA_IP  \
    --token my_HA_token \
	--debug \
	--vad silero \
	--mic-device plughw:CARD=S330 \
	--snd-device sysdefault:CARD=S330 \
	--awake-sound sounds/awake.wav --done-sound sounds/done.wav \
	--noise-suppression 2 --auto-gain 25 --volume-multiplier 6 --volume 0.3
```

Console logs of error:
![image](https://github.com/synesthesiam/homeassistant-satellite/assets/15240222/1c7c303c-2dca-455e-8de4-e03f2425d941)

**Comment by nalf3in** [comment]
Same here unfortunately

**Comment by Fraddles** [comment]
That looks like you are hitting this; https://github.com/synesthesiam/homeassistant-satellite/issues/35

Listed as fixed, but not sure if the docker container has been updated.

I fixed this by putting the required files in a folder and mapping that into the container.  Relevant snippet of docker-compose file;
```
...
    volumes:
      - ./sounds:/sounds
      - ./recordings:/recordings
...
      - --awake-sound=/sounds/awake.wav
      - --done-sound=/sounds/done.wav
#      - --debug
#      - --debug-recording-dir /recordings
...
```
You can just download the files from this repo... or substitute any `.wav` you like I guess...

Cheers

**Comment by khalob** [comment]
Thanks, I'll try that. Much appreciated.

**Comment by khalob** [comment]
Issue still exists in the the latest gchr.io release, but it is solved in the master branch of this github (of which you can clone and build your own docker image locally) so I'll close this. Much appreciated!
