### ISSUE TITLE
Direct wyoming connection (--wake-word wyoming argument) functioning

### ISSUE THREAD

**Issue by lightsabata** [synesthesiam/homeassistant-satellite#76]
hi !
i have an home assitant on a server and a raspberry pi when i have installed homeassistant-satellite and wyoming-porcupine1 on it.
to clean the network traffic i want to both services talk each other directly on the rpi (by localhost).
I read that to enable this function i need to use --wake-word wyoming --wyoming-host --wyoming-port on home assistant-satellite to the wyoming-server.
So after running ``.venv/bin/pip3 install .[wyoming]`` here's the command i use: 
```
script/run --host "MYHAHOST" --token "MYTOKEN" --mic-device "MYMIC" --awake-sound sounds/awake.wav --wake-word wyoming --wyoming-host "localhost" --wyoming-port "10400"
```
but it doesn't seems to work on that command
Of course it work without the --wake-word argument
Is wyoming-pocupine1 is supporting this function or do i need to use another wyoming server ?
am i doing somthing wrong ?

if anyone has encounter the same issue and had managed to solve it, any help will be really appreciated

**Comment by raetha** [comment]
I actually have HA Satellite and Wyoming Porcupine1 working on a Raspberry Pi. I’m not at a computer right now, but will dig up my commands and share them later tonight if I don’t forget. It is relatively simple after I figured out the details.

**Comment by raetha** [comment]
This is still a work in progress, but here is a link to my scripts and config that I'm using to turn a Raspberry Pi into a Home Assistant Satellite with Mopidy, Shairport, Snapclient, etc. I've still been pasting commands in by hand, but almost have the install script completely working.
https://github.com/raetha/Home-Satellite

For your specific situation, these are the arguments I'm passing to use the on-device Wyoming Porcupine1 install:
`--wake-word wyoming --wyoming-host localhost --wyoming-port 10400 --wake-word-id jarvis`

The difference appears to just be that I'm specifying which wake word to use, in my case "jarvis", though it should accept any of the ones built in to Porcupine1.
